ReadMeの執筆
k-gingam/Portfolio pull request #1
Opened 2024-12-14 13:09 UTC by k-gingam

概要
Runteqフォーマットを元に、Readmeの概要を作成。

確認方法
Readme.mdで加筆された内容を確認。

2024-12-15 07:54 UTC, tarakish requested changes
確認しました👍️
> YouTubeの仕組みが大きく変わり、アナリティクスの導入によりユーザーに合わせたおすすめ動画の表示回数が非常に多い、
明らかに再生数を稼ぐためにサムネイルで人を呼び寄せる動画ばかり表示されるなど、収益の為の動画ばかり表示されてしまうようになった為、
昔と比べて一般人が投稿したプレイ動画にたどり着くことが非常に困難な時代になっている。

とありますが、見つけにくくなってしまった「知名度がない一般人が投稿したスーパープレイ」を初期段階ではどのように用意するか、何か考えられていることがあれば追記をいただけますでしょうか？

2024-12-18 12:10 UTC, k-gingam commented
レビューありがとうございます。

> 見つけにくくなってしまった「知名度がない一般人が投稿したスーパープレイ」を初期段階ではどのように用意するか、何か考えられていることがあれば追記をいただけますでしょうか？

こちらについては初期段階でをどう用意すべきか全く決まっておりません。
当サイトを開き、自身のプレイ動画を共有したいユーザーの手によって、「知名度がない一般人が投稿したスーパープレイ」の動画を少しずつ増やすという流れで増やしていこうと想定しております。
その場合は初期段階だと何も動画を用意していない状態となりますが、適当な動画を載せるだけでは見る側がつまらずリピート性がない、逆によく見られる動画を流すとYouTubeで十分という結果になるのは予想出来ている為、
MVPリリースまでに初期段階でどのような動画を用意すべきか、何かいい案がないか模索する予定です。

2024-12-19 05:20 UTC, kenchasonakai commented
> その場合は初期段階だと何も動画を用意していない状態となりますが、適当な動画を載せるだけでは見る側がつまらずリピート性がない、逆によく見られる動画を流すとYouTubeで十分という結果になるのは予想出来ている為、MVPリリースまでに初期段階でどのような動画を用意すべきか、何かいい案がないか模索する予定です。

どんな動画をこのサービスで見られるようにしたいかがしっかり定まっていないとそもそもこのサービスが成り立たないと思いますので効率的な方法でなくともいいので初期データを20件ほど集められるか考えてみてください
ご自身がこのサービスで紹介されるような動画が好きとのことなのでいままで見てきた動画でこのサービスにぴったりなものをピックアップする等でも構いません

2024-12-22 15:34 UTC, k-gingam commented
> どんな動画をこのサービスで見られるようにしたいかがしっかり定まっていないとそもそもこのサービスが成り立たないと思いますので効率的な方法でなくともいいので初期データを20件ほど集められるか考えてみてください

20件ほどならば自身で集めることが可能です。MVPリリースまでにこちらで初期段階に必要なデータを収集しておこうと思います。

2024-12-23 05:40 UTC, TakenakaEri commented
以下の点も確認をお願いします。

> メインターゲット層であるマニアックを先に届けるのは難しい為、先にサブターゲット層である何も知らない人にまずは触れてもらい人海戦術を狙う。
> TikTokのゲーム版として認識してもらいつつ、実はマニアックな動画を探すのにも使えるよということでメインターゲット層に触れてもらう。

ゲームに興味のない人に、ゲーム系の動画を視聴させることは、かなりハードルが高いように思います。
その上で、あまり知識のない人に興味を持たせる戦略を教えて下さい。

また、TikTokのゲーム版とありますが、YouTubeの動画という前提がありますが、こちらはショート動画を共有していくイメージでしょうか？（最初からフルサイズのYouTubeを共有していくのでしょうか？）

現状お持ちのイメージを教えてください。

2024-12-24 16:33 UTC, k-gingam commented
> ゲームに興味のない人に、ゲーム系の動画を視聴させることは、かなりハードルが高いように思います。
> その上で、あまり知識のない人に興味を持たせる戦略を教えて下さい。

あまりゲームをやらない人でも広く知られているゲーム動画をまずは視聴させ、
どんな動画を共有する傾向なのか明示させた上で飽きさせないように工夫したいと考えております。

例えば初めて当サイトに来た人に対して、
「マリオ」や「ゼルダの伝説」など、何をしているか一目で分かりやすいゲームを中心とし、
その中でも印象が強いスーパープレイ動画をいくつかピックアップしてトップページに表示させることで、
本サイトではどんな動画を共有する傾向なのか、サイトを開いてから僅か数回のクリックで分かりやすく明示させたいと思っております。

> また、TikTokのゲーム版とありますが、YouTubeの動画という前提がありますが、こちらはショート動画を共有していくイメージでしょうか？（最初からフルサイズのYouTubeを共有していくのでしょうか？）

こちらは最初からフルサイズのYouTubeの動画を共有する予定となっております。
TikTokのゲーム版と記載した意味については、ジャンル関係なく視聴者を満足させる様々な動画を提供するのがTikTokに対し、当サイトはゲームという要素に特化して視聴者を満足させる動画を提供するという意味で使わさせていただきました。
曖昧の状態で記載して混乱させてしまい、申し訳ありません。

2024-12-26 05:55 UTC, kenchasonakai commented
LGTMです！

バックエンドの機能が薄くなってしまう懸念がありますのでどんな機能があればユーザーは継続して使ってくれるか、ユーザーが視聴した履歴などこのサービスでとれるユーザー周りのデータからどのような機能が提供できそうかなど本リリース時までに作成する機能案を常に考えながら実装を進めていくとよいと思います

2024-12-27 08:36 UTC, merged